### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by PING250** [SilentHeII/Outbreak-Translation#2]
Hello, my English is not good, I am using a translator.
I'm translating the outburst into other languages,
But the text of the file seems to be encrypted. Could you please leave your E-mail contact information to help me complete the rest of the work
You can help me decrypt the Japanese, I will translate

**Comment by krzys837** [comment]
> 

Text is xor encrypted with "ÿ".
Anyway, I want translate outbreak to my language.
I don't know how to edit tex graphics because I need to edit some things and make a font.
If you or SilentHell can help me or whatever - my mail:
krzys837@wp.pl
